apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: app-image
    newName: 123456789012.dkr.ecr.ap-south-1.amazonaws.com/node-app
    newTag: latest
namespace: default
